disabled_rules: # 执行时排除掉的规则（加入表示 不启用该规则）
    - line_length
    - control_statement

opt_in_rules: # 一些规则仅仅是可选的（加入表示 启用该规则）
    - empty_count
    - attributes
    - closure_spacing

included: # 执行 linting 时包含的路径。如果出现这个 `--path` 会被忽略。
    - SwiftLintExample
excluded: # 执行 linting 时忽略的路径。 优先级比 `included` 更高。
    - Carthage
    - Pods
    - Source/ExcludedFolder
    - Source/ExcludedFile.swift
# 可配置的规则可以通过这个配置文件来自定义
# 二进制规则可以设置他们的严格程度
force_cast: warning # 隐式（表示force_cast规则 只会报warning，默认报error ）
force_try:
    severity: warning # 显式
# 同时有警告和错误等级的规则，可以只设置它的警告等级
line_length: 128 # 隐式（超过128 报warning，不报error）
# 可以通过一个数组同时进行隐式设置
type_body_length:
    - 300 # warning
    - 400 # error
# 或者也可以同时进行显式设置
file_length:
    warning: 500
    error: 1200
# 命名规则可以设置最小长度和最大程度的警告/错误
# 此外它们也可以设置排除在外的名字
type_name: # 修改具体的小规则
    min_length: 4 # 只是警告
    max_length: # 警告和错误
        warning: 40
        error: 50
    excluded: iPhone # 排除某个名字
identifier_name:
    min_length: # 只有最小长度
        error: 4 # 只有错误
    allowed_symbols:
        - _ # 除了字母和数字，还允许下划线
#validates_start_with_lowercase: false # 忽略变量首字母小写
    excluded: # 排除某些名字
        - id
        - URL
        - GlobalAPIKey
reporter: "xcode" # 报告类型 (xcode, json, csv, checkstyle, junit, html, emoji)
