# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'XcconfigExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 4.0.0'

  # Pods for XcconfigExample

  target 'XcconfigExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XcconfigExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
